name: Coach
favicon: null
layout_spectrum: 0
typography_spectrum: 0.63189
title: 'Coaching '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f05b2b'
    - '#f58028'
    - '#fac6ad'
    - '#feebe1'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
